### ISSUE TITLE
v2.7 执行报错

### ISSUE THREAD

**Issue by pastay** [xinxin8816/gfriends#23]
```
Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\collections\__init__.py", line 898, in __getitem__
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\collections\__init__.py", line 890, in __missing__
KeyError: 'max_ul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 108, in read_config
  File "configparser.py", line 792, in get
configparser.NoOptionError: No option 'max_ul' in section: '导入设置'

× 无法读取 config.ini。如果这是旧版本的配置文件，请删除后重试。

按任意键退出程序...
```

config.ini 是新版自动生成的

**Comment by xinxin8816** [comment]
已修复，请重新下载 Releases
