### ISSUE TITLE
Error: UNC paths are not supported.  Defaulting to Windows directory.

### ISSUE THREAD

**Issue by richardyu301** [xinxin8816/gfriends#28]
出現以下錯誤請問如何處理?

在CONFIG.INI已經輸入以下資料:
[媒体服务器]
# Emby / Jellyfin 服务器地址
Host_Url = http://192.168.50.104:8096/
	
# Emby / Jellyfin API 密匙
API_ID = XXXXXXX (從EMBY加入API並且拷貝在這裏)

執行EXE顯示下錯誤
'\\Mac\Home\Desktop\Movie Management\Gfriends Inputer'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Traceback (most recent call last):
 File "configparser.py", line 789, in get
 File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\collections\__init__.py", line 898, in __getitem__
 File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\collections\__init__.py", line 890, in __missing__
KeyError: 'host_api'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "Gfriends Inputer.py", line 164, in read_config
 File "configparser.py", line 792, in get
configparser.NoOptionError: No option "host_api" in section: '媒體服務器"

x無法讀取 config.ini。  如果這是舊版本的設置文件, 請刪除後重試。

按任意鍵退出程序...
'\Mac\Home\Desktop\Movie management\Gfriends Inputer'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory

**Comment by xinxin8816** [comment]
目前不支持在 MAC 中嵌套 Windows 运行，请直接使用 MAC 二进制程序
