### ISSUE TITLE
间接性报错

### ISSUE THREAD

**Issue by 9E307** [xinxin8816/gfriends#4]
运行好几，每次都是不同时间段报错，有时候是运行就报错，有时候是运行大半才报错。已经通过clash客户端开启全局模式。
报错信息如下
 During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 719, in urlopen
  File "site-packages\urllib3\util\retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /xinxin8816/gfriends/master/Content/x-E-body/AYU.jpg (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 141, in <module>
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /xinxin8816/gfriends/master/Content/x-E-body/AYU.jpg (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

**Comment by xinxin8816** [comment]
1. 最近GitHubRaw间歇性抽抽
2. 尝试更换代理，在代理软件log中观察：报错里提及的链接是否正确通过代理访问
