### ISSUE TITLE
Gfriends Inputer 图片损坏导致尺寸优化错误

### ISSUE THREAD

**Issue by AAlexDing** [xinxin8816/gfriends#51]
>> 尺寸优化...
!! ./Downloads/田中美佳.jpg 可能已损坏，跳过。
[===========================!            ] (!) 5710/8263 [69%] in 1.3s (4338.66/s)
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 29, in fix_size
  File "PIL\Image.py", line 1133, in crop
  File "PIL\ImageFile.py", line 245, in load
OSError: image file is truncated (11 bytes not processed)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 530, in <module>
  File "Gfriends Inputer.py", line 65, in fix_size
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: './Downloads/田中美佳.jpg' -> './Downloads/Failed/田中美佳.jpg'

× 未知错误，在配置文件中开启 Debug 可获得错误详情。
按任意键退出程序...

**Comment by xinxin8816** [comment]
请尝试用新版Gfriends Inputer
