### ISSUE TITLE
出现未知致命错误，已经打开全局代理

### ISSUE THREAD

**Issue by wangyangwazi** [xinxin8816/gfriends#7]
读取 Emby / Jellyfin 演员...
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 177, in <module>
  File "Gfriends Inputer.py", line 142, in read_persons
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

未知致命错误！

**Comment by xinxin8816** [comment]
请删除config后重新生成，然后使用Notepad++等工具编辑

**Comment by xinxin8816** [comment]
媒体服务器返回了空的演员列表，尝试在控制台计划任务刷新演员。如果还不行请告诉我服务器版本。

**Comment by wangyangwazi** [comment]
问题解决，感觉很玄学，其他的设置都没改动，只是试着在路由器上开启全局模式之后，就一切正常了，也不知道是什么原因

**Comment by xinxin8816** [comment]
可能是本地的全局代理把本机 localhost 127.0.0.1 也给代理了
