### ISSUE TITLE
Gfriends Inputer导入报错

### ISSUE THREAD

**Issue by xyztwwoo** [xinxin8816/gfriends#9]
修改后config.ini无法使用
报错：
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 71, in read_config
  File "configparser.py", line 696, in read
  File "configparser.py", line 1014, in _read
  File "c:\hostedtoolcache\windows\python\3.7.7\x64\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

无法读取 config.ini

修改编码为utf-8后依然报错：

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 71, in read_config
  File "configparser.py", line 696, in read
  File "configparser.py", line 1079, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'config.ini', line: 1
'\ufeff[媒体服务器]\n'

无法读取 config.ini

系统win10，使用最新v2.3
请求支援

**Comment by xinxin8816** [comment]
使用 UTF-8编码 的 Nodepad++ 等工具编辑

**Comment by xinxin8816** [comment]
我会在下次更新时修复这个问题
